remote_theme: pmarsceill/just-the-docs
title: QuickStart for Installing and Using ownCloud
description: ownCloud doc Pages
search_enabled: true
# Aux links for the upper right navigation
aux_links:
    "ownCloud Doc on GitHub":
      - "//github.com/vinlokhand/owncloud-doc"
