remote_theme: pmarsceill/just-the-docs
title: QuickStart
description: ownCloud doc Pages
# Aux links for the upper right navigation
aux_links:
    "Take Me to the Docs on GitHub":
      - "//github.com/vinlokhand/owncloud-doc"
